### ISSUE TITLE
1.10 does not work on Svencoop 5.2/Steam(svends for windows)

### ISSUE THREAD

**Issue by AoiKagase** [alliedmodders/amxmodx#1005]
# Description
Amxmodx outputs an error during server startup and the plugin does not load.

# Environment
  * Operating System version: Windows10 Pro 21H1
  * Game/AppID (with version if applicable): 225840
  * Current AMX Mod X version: 1.10.3.5429 (Changed when compiling.)
  * Current Metamod version: 1.21p38

# Logs
* Please attach in separate files: game output, library logs, kernel logs, and any other supporting information.
* In case of a crash, please attach minidump or dump analyze output.

```L 10/03/2021 - 13:58:05: client_disconnected and client_remove forwards have been disabled - check your gamedata files.```

![image](https://user-images.githubusercontent.com/26139931/135741504-b574b987-b7d9-4f42-9b70-4f006c777349.png)
![image](https://user-images.githubusercontent.com/26139931/135741805-06a9f834-1161-4471-bf5d-0823962c8b78.png)

**Comment by ShootingKing-AM** [comment]
Maybe you didnt install properly, i was able to successfully load all plugins.
And where did you get AMXModx 1.10.**3** from?

```
OS Name:	Microsoft Windows 10 Home
Version:	10.0.19042 Build 19042
```
```
amxx plugins
Currently loaded plugins:
       id  name                    version     author            url                              file         status
 [  1] 0   Admin Base              1.10.0.544  AMXX Dev Team                                      admin.amxx   running
 [  2] 1   Admin Commands          1.10.0.544  AMXX Dev Team                                      admincmd.am  running
 [  3] 2   Admin Help              1.10.0.544  AMXX Dev Team                                      adminhelp.a  running
 [  4] 3   Slots Reservation       1.10.0.544  AMXX Dev Team                                      adminslots.  running
 [  5] 4   Multi-Lingual System    1.10.0.544  AMXX Dev Team                                      multilingua  running
 [  6] 5   Menus Front-End         1.10.0.544  AMXX Dev Team                                      menufront.a  running
 [  7] 6   Commands Menu           1.10.0.544  AMXX Dev Team                                      cmdmenu.amx  running
 [  8] 7   Players Menu            1.10.0.544  AMXX Dev Team                                      plmenu.amxx  running
 [  9] 8   Maps Menu               1.10.0.544  AMXX Dev Team                                      mapsmenu.am  running
 [ 10] 9   Plugin Menu             1.10.0.544  AMXX Dev Team                                      pluginmenu.  running
 [ 11] 10  Admin Chat              1.10.0.544  AMXX Dev Team                                      adminchat.a  running
 [ 12] 11  Anti Flood              1.10.0.544  AMXX Dev Team                                      antiflood.a  running
 [ 13] 12  Scrolling Message       1.10.0.544  AMXX Dev Team                                      scrollmsg.a  running
 [ 14] 13  Info. Messages          1.10.0.544  AMXX Dev Team                                      imessage.am  running
 [ 15] 14  Admin Votes             1.10.0.544  AMXX Dev Team                                      adminvote.a  running
 [ 16] 15  NextMap                 1.10.0.544  AMXX Dev Team                                      nextmap.amx  running
 [ 17] 16  Nextmap Chooser         1.10.0.544  AMXX Dev Team                                      mapchooser.  running
 [ 18] 17  TimeLeft                1.10.0.544  AMXX Dev Team                                      timeleft.am  running
 [ 19] 18  Pause Plugins           1.10.0.544  AMXX Dev Team                                      pausecfg.am  running
 [ 20] 19  Stats Configuration     1.10.0.544  AMXX Dev Team                                      statscfg.am  running
20 plugins, 20 running

version
Protocol version 48
Engine version 5.0.1.7 (svencoop)
Engine build: 11:20:57 Jun 12 2021 (8948)

amxx
Usage: amxx < command > [ argument ]
Commands:
   version                    - display amxx version info
   gpl                        - print the license
   plugins [ criteria ]       - list plugins currently loaded or ones matching given search criteria
   plugin [ id ]              - information about a plugin
   modules                    - list modules currently loaded
   cvars [ plugin ] [ index ] - list cvars handled by amxx or show information about a cvar if index is provided
   cmds [ plugin ]            - list commands registered by plugins
   pause < plugin >           - pause a running plugin
   unpause < plugin >         - unpause a previously paused plugin

amxx version
AMX Mod X 1.10.0.5449 (http://www.amxmodx.org)
Authors:
        David "BAILOPAN" Anderson, Pavol "PM OnoTo" Marko
        Felix "SniperBeamer" Geyer, Jonny "Got His Gun" Bergstrom
        Lukasz "SidLuke" Wlasinski, Christian "Basic-Master" Hammacher
        Borja "faluco" Ferrer, Scott "DS" Ehlert
Compiled: Sep 28 2021 18:40:10
Built from: https://github.com/alliedmodders/amxmodx/commit/3eefe556
Build ID: 5449:3eefe556
Core mode: JIT+ASM32

meta version
Metamod v1.21p38  2018/02/11 (5:13)
by Will Day
   http://www.metamod.org/
 Patch: Metamod-P (mm-p) v38
 by Jussi Kivilinna
    http://metamod-p.sourceforge.net/
compiled: Feb 11 2018, 10:55:08 EET (optimized)

meta list
Currently loaded plugins:
      description      stat pend  file              vers      src   load  unlod
 [ 1] AMX Mod X        RUN   -    amxmodx_mm.dll    v1.10.0.  ini   Start ANY
1 plugins, 1 running

amxx modules
Currently loaded modules:
      name                    version     author               status
0 modules, 0 correct
```

**Comment by AoiKagase** [comment]
The same log is output on the Linux server, but the plugin seems to be loaded.

```
L 10/03/2021 - 16:41:52: client_disconnected and client_remove forwards have been disabled - check your gamedata files.                                                                                           
L 10/03/2021 - 16:41:52: Binding/Hooking cvars have been disabled - check your gamedata files.
```

**Comment by AoiKagase** [comment]
@ShootingKing-AM Changed the version number to 1.10.3 when compiling from github.

**Comment by ShootingKing-AM** [comment]
> @ShootingKing-AM Changed the version number to 1.10.3 when compiling from github.

Maybe can you try official builds and what compiler/version of compiler you are using ?

**Comment by AoiKagase** [comment]
I did a clean install along with a download from the official site, but with similar results.

```
Console initialized.
Threaded networking started successfully.
Protocol version 48
Engine version 5.0.1.7 (svencoop)
Engine build: 11:20:57 Jun 12 2021 (8948)
STEAM Auth Server
Server logging data to file logs\2021-10-03.log
L 03/10/2021 - 17:21:15: Log file started (file "logs\2021-10-03.log") (game "svencoop") (version "48/5.0.1.7/8948")
Initializing IP networking
Local IP address: , SV port: 27020, CL port: -1
Steam P2P networking disabled.

   Metamod version 1.21p38 Copyright (c) 2001-2013 Will Day
     Patch: Metamod-P (mm-p) v38 Copyright (c) 2004-2018 Jussi Kivilinna
   Metamod comes with ABSOLUTELY NO WARRANTY; for details type `meta gpl'.
   This is free software, and you are welcome to redistribute it
   under certain conditions; type `meta gpl' for details.

L 03/10/2021 - 17:21:15: [META] Metamod v1.21p38  2018/02/11
L 03/10/2021 - 17:21:15: [META] by Will Day
L 03/10/2021 - 17:21:15: [META]    http://www.metamod.org/
L 03/10/2021 - 17:21:15: [META]  Patch: Metamod-P (mm-p) v38
L 03/10/2021 - 17:21:15: [META]  by Jussi Kivilinna
L 03/10/2021 - 17:21:15: [META]     http://metamod-p.sourceforge.net/
L 03/10/2021 - 17:21:15: [META] compiled: Feb 11 2018, 10:55:08 EET (optimized)
L 03/10/2021 - 17:21:15: [META] Recognized game 'svencoop'; Autodetection override; using dllfile 'server.dll'
L 03/10/2021 - 17:21:15: [META] Game DLL for 'server.dll (autodetect-override)' loaded successfully
L 03/10/2021 - 17:21:15: [META] ini: Begin reading plugins list: d:/program files (x86)/steam/steamapps/common/sven co-op/svencoop/addons/metamod/plugins.ini
L 03/10/2021 - 17:21:15: [META] ini: Read plugin config for: <amxmodx_mm.dll>
L 03/10/2021 - 17:21:15: [META] ini: Finished reading plugins list: d:/program files (x86)/steam/steamapps/common/sven co-op/svencoop/addons/metamod/plugins.ini; Found 1 plugins to load
L 03/10/2021 - 17:21:15: [META] dll: Loading plugins...

   AMX Mod X version 1.10.0.5449 Copyright (c) 2004-2015 AMX Mod X Development Team
   AMX Mod X comes with ABSOLUTELY NO WARRANTY; for details type `amxx gpl'.
   This is free software and you are welcome to redistribute it under
   certain conditions; type 'amxx gpl' for details.

L 10/03/2021 - 17:21:15: client_disconnected and client_remove forwards have been disabled - check your gamedata files.
L 10/03/2021 - 17:21:15: Binding/Hooking cvars have been disabled - check your gamedata files.
L 03/10/2021 - 17:21:15: [META] dll: Loaded plugin 'AMX Mod X': AMX Mod X v1.10.0.5449 Mar 12 2021, AMX Mod X Dev Team
L 03/10/2021 - 17:21:15: [META] dll: Finished loading 1 plugins
L 03/10/2021 - 17:21:15: Log file closed
Server logging data to file logs\2021-10-03.log
L 03/10/2021 - 17:21:15: Log file started (file "logs\2021-10-03.log") (game "svencoop") (version "48/5.0.1.7/8948")
```

```
meta version
Metamod v1.21p38  2018/02/11 (5:13)
by Will Day
   http://www.metamod.org/
 Patch: Metamod-P (mm-p) v38
 by Jussi Kivilinna
    http://metamod-p.sourceforge.net/
compiled: Feb 11 2018, 10:55:08 EET (optimized)

meta list
Currently loaded plugins:
      description      stat pend  file              vers      src   load  unlod
 [ 1] AMX Mod X        RUN   -    amxmodx_mm.dll    v1.10.0.  ini   Start ANY
1 plugins, 1 running

amxx version
AMX Mod X 1.10.0.5449 (http://www.amxmodx.org)
Authors:
        David "BAILOPAN" Anderson, Pavol "PM OnoTo" Marko
        Felix "SniperBeamer" Geyer, Jonny "Got His Gun" Bergstrom
        Lukasz "SidLuke" Wlasinski, Christian "Basic-Master" Hammacher
        Borja "faluco" Ferrer, Scott "DS" Ehlert
Compiled: Sep 28 2021 18:40:10
Built from: https://github.com/alliedmodders/amxmodx/commit/3eefe556
Build ID: 5449:3eefe556
Core mode: JIT+ASM32

amxx modules
Currently loaded modules:
      name                    version     author               status
0 modules, 0 correct

amxx plugins
Currently loaded plugins:
       id  name                    version     author            url                              file         status
0 plugins, 0 running

```

**Comment by ShootingKing-AM** [comment]
What are your `cmd line args` to start the server ?

**Comment by AoiKagase** [comment]
> What are your `cmd line args` to start the server ?
```
"D:\Program Files (x86)\Steam\steamapps\common\Sven Co-op\svends.exe" -console +port 27020 +map stadium4 +log on
```

**Comment by AoiKagase** [comment]
I tried the same on a Linux server, but the above gamedata error is output.
But the plugin is loaded.

**Comment by ShootingKing-AM** [comment]
> > What are your `cmd line args` to start the server ?
> 
> ```
> "D:\Program Files (x86)\Steam\steamapps\common\Sven Co-op\svends.exe" -console +port 27020 +map stadium4 +log on
> ```

Still its loading all plugins for me.

```
Console initialized.
Threaded networking started successfully.
Protocol version 48
Engine version 5.0.1.7 (svencoop)
Engine build: 11:20:57 Jun 12 2021 (8948)
STEAM Auth Server
Server logging data to file logs\2021-10-03.log
L 03/10/2021 - 14:05:16: Log file started (file "logs\2021-10-03.log") (game "svencoop") (version "48/5.0.1.7/8948")
Initializing IP networking
Local IP address: , SV port: 27020, CL port: -1
Steam P2P networking disabled.

   Metamod version 1.21p38 Copyright (c) 2001-2013 Will Day
     Patch: Metamod-P (mm-p) v38 Copyright (c) 2004-2018 Jussi Kivilinna
   Metamod comes with ABSOLUTELY NO WARRANTY; for details type `meta gpl'.
   This is free software, and you are welcome to redistribute it
   under certain conditions; type `meta gpl' for details.

L 03/10/2021 - 14:05:16: [META] Metamod v1.21p38  2018/02/11
L 03/10/2021 - 14:05:16: [META] by Will Day
L 03/10/2021 - 14:05:16: [META]    http://www.metamod.org/
L 03/10/2021 - 14:05:16: [META]  Patch: Metamod-P (mm-p) v38
L 03/10/2021 - 14:05:16: [META]  by Jussi Kivilinna
L 03/10/2021 - 14:05:16: [META]     http://metamod-p.sourceforge.net/
L 03/10/2021 - 14:05:16: [META] compiled: Feb 11 2018, 10:55:08 EET (optimized)
L 03/10/2021 - 14:05:16: [META] Recognized game 'svencoop'; Autodetection override; using dllfile 'server.dll'
L 03/10/2021 - 14:05:16: [META] Game DLL for 'server.dll (autodetect-override)' loaded successfully
L 03/10/2021 - 14:05:16: [META] ini: Begin reading plugins list: c:/steancmd/sven/svencoop/addons/metamod/plugins.ini
L 03/10/2021 - 14:05:16: [META] ini: Read plugin config for: <amxmodx_mm.dll>
L 03/10/2021 - 14:05:16: [META] ini: Finished reading plugins list: c:/steancmd/sven/svencoop/addons/metamod/plugins.ini; Found 1 plugins to load
L 03/10/2021 - 14:05:16: [META] dll: Loading plugins...

   AMX Mod X version 1.10.0.5449 Copyright (c) 2004-2015 AMX Mod X Development Team
   AMX Mod X comes with ABSOLUTELY NO WARRANTY; for details type `amxx gpl'.
   This is free software and you are welcome to redistribute it under
   certain conditions; type 'amxx gpl' for details.

L 10/03/2021 - 14:05:17: client_disconnected and client_remove forwards have been disabled - check your gamedata files.
L 10/03/2021 - 14:05:17: Binding/Hooking cvars have been disabled - check your gamedata files.
L 03/10/2021 - 14:05:17: [META] dll: Loaded plugin 'AMX Mod X': AMX Mod X v1.10.0.5449 Mar 12 2021, AMX Mod X Dev Team
L 03/10/2021 - 14:05:17: [META] dll: Finished loading 1 plugins
L 03/10/2021 - 14:05:17: Log file closed
Server logging data to file logs\2021-10-03.log
L 03/10/2021 - 14:05:17: Log file started (file "logs\2021-10-03.log") (game "svencoop") (version "48/5.0.1.7/8948")
L 03/10/2021 - 14:05:17: Loading map "stadium4"
L 03/10/2021 - 14:05:17: Server cvars start
L 03/10/2021 - 14:05:17: Server cvar "adminsfile" = "admins.txt"
L 03/10/2021 - 14:05:17: Server cvar "allow_spectators" = "1.0"
L 03/10/2021 - 14:05:17: Server cvar "amx_client_languages" = "1"
L 03/10/2021 - 14:05:17: Server cvar "amx_language" = "en"
L 03/10/2021 - 14:05:17: Server cvar "amxmodx_version" = ""
L 03/10/2021 - 14:05:17: Server cvar "coop" = "0"
L 03/10/2021 - 14:05:17: Server cvar "deathmatch" = "1"
L 03/10/2021 - 14:05:17: Server cvar "edgefriction" = "2"
L 03/10/2021 - 14:05:17: Server cvar "gamebuild" = "7016"
L 03/10/2021 - 14:05:17: Server cvar "gamename" = "Sven Co-op"
L 03/10/2021 - 14:05:17: Server cvar "gameversion" = "5.25"
L 03/10/2021 - 14:05:17: Server cvar "gameversionnum" = "5.25"
L 03/10/2021 - 14:05:17: Server cvar "mapvotecfgfile" = "mapvote.cfg"
L 03/10/2021 - 14:05:17: Server cvar "max_queries_sec" = "3.0"
L 03/10/2021 - 14:05:17: Server cvar "max_queries_sec_global" = "30"
L 03/10/2021 - 14:05:17: Server cvar "max_queries_window" = "60"
L 03/10/2021 - 14:05:17: Server cvar "metamod_version" = "1.21p38"
L 03/10/2021 - 14:05:17: Server cvar "mp_banana" = "1.0"
L 03/10/2021 - 14:05:17: Server cvar "mp_consistency" = "1"
L 03/10/2021 - 14:05:17: Server cvar "mp_footsteps" = "1"
L 03/10/2021 - 14:05:17: Server cvar "mp_logfile" = "1"
L 03/10/2021 - 14:05:17: Server cvar "mp_nextmap_cycle" = ""
L 03/10/2021 - 14:05:17: Server cvar "mp_notimelimit" = "0.0"
L 03/10/2021 - 14:05:17: Server cvar "pausable" = "0"
L 03/10/2021 - 14:05:17: Server cvar "skillcfgfile" = "skill.cfg"
L 03/10/2021 - 14:05:17: Server cvar "sv_accelerate" = "10"
L 03/10/2021 - 14:05:17: Server cvar "sv_admin_icon" = "gfx/icons/admin.tga"
L 03/10/2021 - 14:05:17: Server cvar "sv_aim" = "1"
L 03/10/2021 - 14:05:17: Server cvar "sv_airaccelerate" = "10"
L 03/10/2021 - 14:05:17: Server cvar "sv_allowupload" = "1"
L 03/10/2021 - 14:05:17: Server cvar "sv_bounce" = "1"
L 03/10/2021 - 14:05:17: Server cvar "sv_cheats" = "0"
L 03/10/2021 - 14:05:17: Server cvar "sv_clienttrace" = "1"
L 03/10/2021 - 14:05:17: Server cvar "sv_contact" = ""
L 03/10/2021 - 14:05:17: Server cvar "sv_friction" = "4"
L 03/10/2021 - 14:05:17: Server cvar "sv_gravity" = "800"
L 03/10/2021 - 14:05:17: Server cvar "sv_logblocks" = "0"
L 03/10/2021 - 14:05:17: Server cvar "sv_maxrate" = "0"
L 03/10/2021 - 14:05:17: Server cvar "sv_maxspeed" = "320"
L 03/10/2021 - 14:05:17: Server cvar "sv_minrate" = "0"
L 03/10/2021 - 14:05:17: Server cvar "sv_password" = ""
L 03/10/2021 - 14:05:17: Server cvar "sv_proxies" = "1"
L 03/10/2021 - 14:05:17: Server cvar "sv_stepsize" = "18"
L 03/10/2021 - 14:05:17: Server cvar "sv_stopspeed" = "100"
L 03/10/2021 - 14:05:17: Server cvar "sv_uploadmax" = "0.5"
L 03/10/2021 - 14:05:17: Server cvar "sv_voiceenable" = "1"
L 03/10/2021 - 14:05:17: Server cvar "sv_wateraccelerate" = "10"
L 03/10/2021 - 14:05:17: Server cvar "sv_waterfriction" = "1"
L 03/10/2021 - 14:05:17: Server cvars end
L 10/03/2021 - 14:05:18: -------- Mapchange to stadium4 --------
L 03/10/2021 - 14:05:18: Server cvar "amxmodx_version" = "1.10.0.5449"
L 03/10/2021 - 14:05:18: Server cvar "mp_consistency" = "0"
L 03/10/2021 - 14:05:18: Log file closed
Server logging data to file logs\2021-10-03.log
L 03/10/2021 - 14:05:18: Log file started (file "logs\2021-10-03.log") (game "svencoop") (version "48/5.0.1.7/8948")
L 03/10/2021 - 14:05:18: Server cvar "sv_aim" = "0"
couldn't exec banned.cfg
couldn't exec listip.cfg
L 03/10/2021 - 14:05:18: Server cvar "mp_banana" = "1"
L 03/10/2021 - 14:05:18: Server cvar "sv_maxspeed" = "270"
L 03/10/2021 - 14:05:18: Server is empty, map will end in 10.00 minute(s) if nobody connects.
[AMXX] Loaded 1 admin from file
L 03/10/2021 - 14:05:20: Server cvar "amx_nextmap" = "abandoned"
Can't precache excluded file: maps/stadium4.cfg
L 03/10/2021 - 14:05:20: Started map "stadium4" (CRC "-2139707026")
Executing AMX Mod X Configuration File
Scrolling message displaying frequency: 10:00 minutes
L 03/10/2021 - 14:05:20: Log file closed
Server logging data to file logs\2021-10-03.log
L 03/10/2021 - 14:05:20: Log file started (file "logs\2021-10-03.log") (game "svencoop") (version "48/5.0.1.7/8948")
couldn't exec banned.cfg
couldn't exec listip.cfg
Connection to Steam servers successful.
   VAC secure mode is activated.

amxx plugins
Currently loaded plugins:
       id  name                    version     author            url                              file         status
 [  1] 0   Admin Base              1.10.0.544  AMXX Dev Team                                      admin.amxx   running
 [  2] 1   Admin Commands          1.10.0.544  AMXX Dev Team                                      admincmd.am  running
 [  3] 2   Admin Help              1.10.0.544  AMXX Dev Team                                      adminhelp.a  running
 [  4] 3   Slots Reservation       1.10.0.544  AMXX Dev Team                                      adminslots.  running
 [  5] 4   Multi-Lingual System    1.10.0.544  AMXX Dev Team                                      multilingua  running
 [  6] 5   Menus Front-End         1.10.0.544  AMXX Dev Team                                      menufront.a  running
 [  7] 6   Commands Menu           1.10.0.544  AMXX Dev Team                                      cmdmenu.amx  running
 [  8] 7   Players Menu            1.10.0.544  AMXX Dev Team                                      plmenu.amxx  running
 [  9] 8   Maps Menu               1.10.0.544  AMXX Dev Team                                      mapsmenu.am  running
 [ 10] 9   Plugin Menu             1.10.0.544  AMXX Dev Team                                      pluginmenu.  running
 [ 11] 10  Admin Chat              1.10.0.544  AMXX Dev Team                                      adminchat.a  running
 [ 12] 11  Anti Flood              1.10.0.544  AMXX Dev Team                                      antiflood.a  running
 [ 13] 12  Scrolling Message       1.10.0.544  AMXX Dev Team                                      scrollmsg.a  running
 [ 14] 13  Info. Messages          1.10.0.544  AMXX Dev Team                                      imessage.am  running
 [ 15] 14  Admin Votes             1.10.0.544  AMXX Dev Team                                      adminvote.a  running
 [ 16] 15  NextMap                 1.10.0.544  AMXX Dev Team                                      nextmap.amx  running
 [ 17] 16  Nextmap Chooser         1.10.0.544  AMXX Dev Team                                      mapchooser.  running
 [ 18] 17  TimeLeft                1.10.0.544  AMXX Dev Team                                      timeleft.am  running
 [ 19] 18  Pause Plugins           1.10.0.544  AMXX Dev Team                                      pausecfg.am  running
 [ 20] 19  Stats Configuration     1.10.0.544  AMXX Dev Team                                      statscfg.am  running
20 plugins, 20 running

amxx version
AMX Mod X 1.10.0.5449 (http://www.amxmodx.org)
Authors:
        David "BAILOPAN" Anderson, Pavol "PM OnoTo" Marko
        Felix "SniperBeamer" Geyer, Jonny "Got His Gun" Bergstrom
        Lukasz "SidLuke" Wlasinski, Christian "Basic-Master" Hammacher
        Borja "faluco" Ferrer, Scott "DS" Ehlert
Compiled: Sep 28 2021 18:40:10
Built from: https://github.com/alliedmodders/amxmodx/commit/3eefe556
Build ID: 5449:3eefe556
Core mode: JIT+ASM32

meta version
Metamod v1.21p38  2018/02/11 (5:13)
by Will Day
   http://www.metamod.org/
 Patch: Metamod-P (mm-p) v38
 by Jussi Kivilinna
    http://metamod-p.sourceforge.net/
compiled: Feb 11 2018, 10:55:08 EET (optimized)

meta list
Currently loaded plugins:
      description      stat pend  file              vers      src   load  unlod
 [ 1] AMX Mod X        RUN   -    amxmodx_mm.dll    v1.10.0.  ini   Start ANY
1 plugins, 1 running

amxx modules
Currently loaded modules:
      name                    version     author               status
0 modules, 0 correct
```
I guess we need to log more data from AMXModX core, i dont see anyother way.

**Comment by ShootingKing-AM** [comment]
Is it solved now @AoiKagase ?

**Comment by AoiKagase** [comment]
> Is it solved now @AoiKagase ?
No. It seems to be working somehow on the Linux server, so I am testing it there.
It still doesn't seem to work on Windows.

**Comment by AoiKagase** [comment]
There was a difference in behavior between SteamCMD and SteamClient.
It seems to work in the case of SteamCMD.
I was using the SvenDS that exists in Client.

**Comment by AoiKagase** [comment]
Sorry. It was my mistake.
There were two game_dlls in liblist.gam.
```
gamedll "dlls/server.dll"
gamedll "addons/metamod/dlls/metamod.dll"
```

I commented out the server.dll and it worked.
I will close this issue.
